version: "3.8"

services:
  api_gateway:
    build: ./api_gateway
    ports: 
      - "8080:8080"
    depends_on:
      - auth_service
      - get_service
      - code_evaluations_service
      - collaboration_service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
  get_service:
    build: ./get_service
    ports:
      - "8002:8002"
  code_evaluations_service:
    build: ./code_evaluations_service
    ports:
      - "8003:8003"
  collaboration_service:
    build: ./collaboration_service
    ports:
      - "8004:8004"