# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: problem.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'problem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproblem.proto\x12\x07problem\"9\n\x11GetProblemRequest\x12\x12\n\nproblem_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"\x99\x01\n\x12GetProblemResponse\x12\x12\n\nproblem_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0cinput_schema\x18\x03 \x01(\t\x12\x19\n\x11official_solution\x18\x04 \x01(\t\x12\x13\n\x0b\x63onstraints\x18\x05 \x01(\t\x12\x1a\n\x12\x65xecution_template\x18\x06 \x01(\t2[\n\x0eProblemService\x12I\n\x0eGetProblemById\x12\x1a.problem.GetProblemRequest\x1a\x1b.problem.GetProblemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'problem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROBLEMREQUEST']._serialized_start=26
  _globals['_GETPROBLEMREQUEST']._serialized_end=83
  _globals['_GETPROBLEMRESPONSE']._serialized_start=86
  _globals['_GETPROBLEMRESPONSE']._serialized_end=239
  _globals['_PROBLEMSERVICE']._serialized_start=241
  _globals['_PROBLEMSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
